<a href="https://colab.research.google.com/github/atempvisit/learning-deep_learning/blob/main/Module_11_Pytorch_Training_Pipeline_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [6]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train

array([[-0.9320971 ,  0.45957378, -0.85730746, ...,  0.36209595,
         0.04914927,  0.61745095],
       [ 2.0016524 , -0.97653116,  1.9688766 , ...,  1.17560982,
        -0.31281538,  0.11121652],
       [-0.68151772, -0.09418828, -0.71029702, ..., -0.73764873,
        -0.61445259, -0.25122579],
       ...,
       [-0.39152137,  0.04367779, -0.41871953, ..., -0.81704889,
         0.58900253, -0.39017098],
       [-0.41967636,  2.31617024, -0.47247403, ..., -0.79993808,
        -0.81245035, -1.06389361],
       [-0.27890143, -0.53535972, -0.34216007, ..., -0.32263658,
        -0.65931146, -0.45048828]])

In [10]:
y_train

41     M
372    M
211    B
474    B
345    B
      ..
179    B
454    B
436    B
552    B
224    B
Name: diagnosis, Length: 455, dtype: object

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [13]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [14]:
type(X_train_tensor)

torch.Tensor

In [16]:
X_train.shape[1]

30

In [34]:
class MySimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)

    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 10e-7

    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    loss = -(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()

    return loss

In [27]:
torch.rand(30, 1)

tensor([[0.3048],
        [0.1217],
        [0.1170],
        [0.9493],
        [0.5531],
        [0.0660],
        [0.0065],
        [0.7648],
        [0.9910],
        [0.8844],
        [0.7217],
        [0.1611],
        [0.9865],
        [0.6064],
        [0.3714],
        [0.6832],
        [0.7961],
        [0.5731],
        [0.5332],
        [0.4641],
        [0.5555],
        [0.5141],
        [0.0329],
        [0.3253],
        [0.4111],
        [0.8275],
        [0.9310],
        [0.5436],
        [0.7405],
        [0.5861]])

In [28]:
model = MySimpleNN(X_train_tensor)

In [30]:
model.weights

tensor([[0.2198],
        [0.4357],
        [0.8652],
        [0.6475],
        [0.3263],
        [0.0448],
        [0.4966],
        [0.7148],
        [0.3625],
        [0.4413],
        [0.4591],
        [0.8752],
        [0.2493],
        [0.4449],
        [0.3763],
        [0.5060],
        [0.5560],
        [0.3169],
        [0.9370],
        [0.9184],
        [0.3511],
        [0.7655],
        [0.6489],
        [0.2306],
        [0.9809],
        [0.4591],
        [0.7420],
        [0.3722],
        [0.9441],
        [0.0592]], dtype=torch.float64, requires_grad=True)

In [31]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [35]:
learning_rate = 0.01

epochs = 25

In [36]:
model = MySimpleNN(X_train_tensor)

for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(X_train_tensor)


  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # update weights
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradient

  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'epoch: {epoch+1}, loss: {loss.item()}')

epoch: 1, loss: 3.197978517695731
epoch: 2, loss: 3.184986452927357
epoch: 3, loss: 3.172008119164295
epoch: 4, loss: 3.1590437084156706
epoch: 5, loss: 3.146072880140056
epoch: 6, loss: 3.1329102733441294
epoch: 7, loss: 3.119559668254463
epoch: 8, loss: 3.1059619852673546
epoch: 9, loss: 3.0922359937939867
epoch: 10, loss: 3.0783428700130195
epoch: 11, loss: 3.0642786915501117
epoch: 12, loss: 3.050231468710296
epoch: 13, loss: 3.0362014453009745
epoch: 14, loss: 3.022188867840965
epoch: 15, loss: 3.008187285032316
epoch: 16, loss: 2.9940589577278214
epoch: 17, loss: 2.9799488912791405
epoch: 18, loss: 2.9657567638206013
epoch: 19, loss: 2.951472383748754
epoch: 20, loss: 2.9372074211941683
epoch: 21, loss: 2.922962152992797
epoch: 22, loss: 2.9087368593365657
epoch: 23, loss: 2.894531823872997
epoch: 24, loss: 2.880347333809346
epoch: 25, loss: 2.866100691643472

In [49]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'accuracy: {accuracy.item()}')

accuracy: 0.6240381598472595