<a href="https://colab.research.google.com/github/atempvisit/learning-deep_learning/blob/main/Module_15_11_Improvement_of_our_Training_Pipeline_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-0.67224839, -1.05490225, -0.63969871, ..., -0.12739545,
        -0.49572282,  0.8059317 ],
       [-1.25141582, -1.69759829, -1.27335367, ..., -1.76305866,
         0.29249254, -0.1372147 ],
       [-0.3395598 , -1.42587018, -0.40507398, ..., -0.93190631,
        -0.95984164, -0.81182636],
       ...,
       [-0.68671311,  1.2488795 , -0.63717586, ...,  0.26293327,
        -0.18263927,  0.85559971],
       [-0.94418515, -2.23160308, -0.95673643, ..., -1.05008918,
        -1.30439087, -0.38391735],
       [ 1.14162764,  0.33209251,  1.13007816, ...,  0.54328842,
         0.52219203, -0.42430672]])

In [9]:
y_train

510    B
140    B
287    B
513    B
132    M
      ..
345    B
253    M
537    B
166    B
492    M
Name: diagnosis, Length: 455, dtype: object

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1])

In [12]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

In [13]:
type(X_train_tensor)

torch.Tensor

data set

In [14]:
from torch.utils.data import Dataset, DataLoader

In [15]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, idx):
    return self.features[idx], self.labels[idx]

In [31]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [32]:
len(train_dataset)

455

In [33]:
train_dataset[2]

(tensor([-0.3396, -1.4259, -0.4051, -0.3846, -1.9162, -1.2701, -0.8220, -0.9648,
         -1.7406, -0.9761, -0.9316, -1.4656, -0.8923, -0.6437, -0.7774, -0.6604,
         -0.4910, -0.9660, -0.5421, -0.6318, -0.5428, -1.6381, -0.5870, -0.5289,
         -1.6201, -0.8734, -0.7278, -0.9319, -0.9598, -0.8118]),
 tensor(0.))

data loader

In [34]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [16]:
X_train.shape[1]

30

In [17]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [18]:
torch.rand(30, 1)

tensor([[0.2623],
        [0.2212],
        [0.5258],
        [0.6348],
        [0.9198],
        [0.9270],
        [0.9531],
        [0.0286],
        [0.1108],
        [0.9205],
        [0.9977],
        [0.1331],
        [0.5076],
        [0.1254],
        [0.1965],
        [0.2141],
        [0.6847],
        [0.4982],
        [0.7115],
        [0.7338],
        [0.4112],
        [0.2268],
        [0.5958],
        [0.9527],
        [0.2893],
        [0.1652],
        [0.3766],
        [0.1285],
        [0.1669],
        [0.6265]])

In [19]:
learning_rate = 0.01

epochs = 25

In [20]:
loss_function = nn.BCELoss()

In [21]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [22]:
X_test_tensor.shape[1]

30

In [41]:
model = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)


    # loss calculate
    loss = loss_function(y_pred, batch_labels.reshape(-1, 1))


    # zero gradient

    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # update weights
    optimizer.step()

    # print loss

    print(f'epoch: {epoch+1}, loss: {loss.item()}')

epoch: 1, loss: 0.7656455636024475
epoch: 1, loss: 0.7914583086967468
epoch: 1, loss: 0.6956749558448792
epoch: 1, loss: 0.6660232543945312
epoch: 1, loss: 0.6862051486968994
epoch: 1, loss: 0.6595140695571899
epoch: 1, loss: 0.6477245688438416
epoch: 1, loss: 0.5902938842773438
epoch: 1, loss: 0.687648594379425
epoch: 1, loss: 0.5266412496566772
epoch: 1, loss: 0.5803008079528809
epoch: 1, loss: 0.6081978678703308
epoch: 1, loss: 0.5571932792663574
epoch: 1, loss: 0.5334975719451904
epoch: 1, loss: 0.5819818377494812
epoch: 2, loss: 0.5357387065887451
epoch: 2, loss: 0.5253884792327881
epoch: 2, loss: 0.5197640061378479
epoch: 2, loss: 0.49814820289611816
epoch: 2, loss: 0.4836549162864685
epoch: 2, loss: 0.4841032028198242
epoch: 2, loss: 0.456667959690094
epoch: 2, loss: 0.4825662076473236
epoch: 2, loss: 0.46170198917388916
epoch: 2, loss: 0.42499837279319763
epoch: 2, loss: 0.46674051880836487
epoch: 2, loss: 0.48178908228874207
epoch: 2, loss: 0.4557758867740631
epoch: 2, loss: 0.4168432652950287
epoch: 2, loss: 0.4532439708709717
epoch: 3, loss: 0.4354691803455353
epoch: 3, loss: 0.38794320821762085
epoch: 3, loss: 0.43495818972587585
epoch: 3, loss: 0.4479525685310364
epoch: 3, loss: 0.3354794681072235
epoch: 3, loss: 0.3508261442184448
epoch: 3, loss: 0.45114004611968994
epoch: 3, loss: 0.3996151387691498
epoch: 3, loss: 0.40516865253448486
epoch: 3, loss: 0.35075095295906067
epoch: 3, loss: 0.3678912818431854
epoch: 3, loss: 0.3792198896408081
epoch: 3, loss: 0.34745052456855774
epoch: 3, loss: 0.4494927227497101
epoch: 3, loss: 0.24306437373161316
epoch: 4, loss: 0.36751091480255127
epoch: 4, loss: 0.37718865275382996
epoch: 4, loss: 0.3561599552631378
epoch: 4, loss: 0.3582983911037445
epoch: 4, loss: 0.3015230894088745
epoch: 4, loss: 0.32920041680336
epoch: 4, loss: 0.3043178617954254
epoch: 4, loss: 0.32587313652038574
epoch: 4, loss: 0.4004213213920593
epoch: 4, loss: 0.32654184103012085
epoch: 4, loss: 0.3106021583080292
epoch: 4, loss: 0.35528287291526794
epoch: 4, loss: 0.30741772055625916
epoch: 4, loss: 0.38571062684059143
epoch: 4, loss: 0.2855882942676544
epoch: 5, loss: 0.41112253069877625
epoch: 5, loss: 0.33577319979667664
epoch: 5, loss: 0.28655365109443665
epoch: 5, loss: 0.313977986574173
epoch: 5, loss: 0.28981509804725647
epoch: 5, loss: 0.33752012252807617
epoch: 5, loss: 0.25243282318115234
epoch: 5, loss: 0.35350528359413147
epoch: 5, loss: 0.24491386115550995
epoch: 5, loss: 0.3239172101020813
epoch: 5, loss: 0.335089772939682
epoch: 5, loss: 0.24930506944656372
epoch: 5, loss: 0.2542952001094818
epoch: 5, loss: 0.32568591833114624
epoch: 5, loss: 0.28857892751693726
epoch: 6, loss: 0.2868257462978363
epoch: 6, loss: 0.31698018312454224
epoch: 6, loss: 0.28390392661094666
epoch: 6, loss: 0.291414737701416
epoch: 6, loss: 0.3938828706741333
epoch: 6, loss: 0.2356564849615097
epoch: 6, loss: 0.27552422881126404
epoch: 6, loss: 0.19952569901943207
epoch: 6, loss: 0.3033056855201721
epoch: 6, loss: 0.313091903924942
epoch: 6, loss: 0.23471543192863464
epoch: 6, loss: 0.32319149374961853
epoch: 6, loss: 0.27447962760925293
epoch: 6, loss: 0.22695079445838928
epoch: 6, loss: 0.27320876717567444
epoch: 7, loss: 0.26631665229797363
epoch: 7, loss: 0.2071952372789383
epoch: 7, loss: 0.2810453772544861
epoch: 7, loss: 0.2591729164123535
epoch: 7, loss: 0.2793736457824707
epoch: 7, loss: 0.2945902347564697
epoch: 7, loss: 0.29371002316474915
epoch: 7, loss: 0.22593319416046143
epoch: 7, loss: 0.2856386601924896
epoch: 7, loss: 0.2426004707813263
epoch: 7, loss: 0.2092800885438919
epoch: 7, loss: 0.28672096133232117
epoch: 7, loss: 0.2532060742378235
epoch: 7, loss: 0.300578773021698
epoch: 7, loss: 0.2621917426586151
epoch: 8, loss: 0.244087815284729
epoch: 8, loss: 0.22522899508476257
epoch: 8, loss: 0.2927762567996979
epoch: 8, loss: 0.289132684469223
epoch: 8, loss: 0.1920085847377777
epoch: 8, loss: 0.2557445168495178
epoch: 8, loss: 0.1847585290670395
epoch: 8, loss: 0.1970379799604416
epoch: 8, loss: 0.24487750232219696
epoch: 8, loss: 0.3749132752418518
epoch: 8, loss: 0.21821068227291107
epoch: 8, loss: 0.2628088593482971
epoch: 8, loss: 0.2960355877876282
epoch: 8, loss: 0.19321556389331818
epoch: 8, loss: 0.2125401645898819
epoch: 9, loss: 0.20942722260951996
epoch: 9, loss: 0.27823182940483093
epoch: 9, loss: 0.23889416456222534
epoch: 9, loss: 0.20744363963603973
epoch: 9, loss: 0.16402313113212585
epoch: 9, loss: 0.2057950347661972
epoch: 9, loss: 0.29385867714881897
epoch: 9, loss: 0.18801860511302948
epoch: 9, loss: 0.2307593822479248
epoch: 9, loss: 0.3125201463699341
epoch: 9, loss: 0.2550615668296814
epoch: 9, loss: 0.21158570051193237
epoch: 9, loss: 0.25459063053131104
epoch: 9, loss: 0.24900564551353455
epoch: 9, loss: 0.17176569998264313
epoch: 10, loss: 0.20878291130065918
epoch: 10, loss: 0.2150358259677887
epoch: 10, loss: 0.20941410958766937
epoch: 10, loss: 0.22291015088558197
epoch: 10, loss: 0.24922753870487213
epoch: 10, loss: 0.21917712688446045
epoch: 10, loss: 0.18511757254600525
epoch: 10, loss: 0.186483696103096
epoch: 10, loss: 0.24313782155513763
epoch: 10, loss: 0.3565181493759155
epoch: 10, loss: 0.260682612657547
epoch: 10, loss: 0.22607597708702087
epoch: 10, loss: 0.15746307373046875
epoch: 10, loss: 0.15619458258152008
epoch: 10, loss: 0.3984096050262451
epoch: 11, loss: 0.22827008366584778
epoch: 11, loss: 0.17478600144386292
epoch: 11, loss: 0.2662920355796814
epoch: 11, loss: 0.23594355583190918
epoch: 11, loss: 0.14837731420993805
epoch: 11, loss: 0.2166346162557602
epoch: 11, loss: 0.25140291452407837
epoch: 11, loss: 0.19705744087696075
epoch: 11, loss: 0.1503501981496811
epoch: 11, loss: 0.2489273101091385
epoch: 11, loss: 0.25846555829048157
epoch: 11, loss: 0.21163944900035858
epoch: 11, loss: 0.2205640971660614
epoch: 11, loss: 0.21451547741889954
epoch: 11, loss: 0.13732275366783142
epoch: 12, loss: 0.17840410768985748
epoch: 12, loss: 0.280041366815567
epoch: 12, loss: 0.23274359107017517
epoch: 12, loss: 0.14172245562076569
epoch: 12, loss: 0.24716955423355103
epoch: 12, loss: 0.19400110840797424
epoch: 12, loss: 0.2048710584640503
epoch: 12, loss: 0.22309967875480652
epoch: 12, loss: 0.23583100736141205
epoch: 12, loss: 0.2084123194217682
epoch: 12, loss: 0.16048866510391235
epoch: 12, loss: 0.28308480978012085
epoch: 12, loss: 0.17100858688354492
epoch: 12, loss: 0.138148233294487
epoch: 12, loss: 0.17667926847934723
epoch: 13, loss: 0.19548127055168152
epoch: 13, loss: 0.17564736306667328
epoch: 13, loss: 0.20695918798446655
epoch: 13, loss: 0.3027341961860657
epoch: 13, loss: 0.2155800610780716
epoch: 13, loss: 0.17739787697792053
epoch: 13, loss: 0.12636850774288177
epoch: 13, loss: 0.2059180736541748
epoch: 13, loss: 0.2290797382593155
epoch: 13, loss: 0.22495076060295105
epoch: 13, loss: 0.23565734922885895
epoch: 13, loss: 0.21963919699192047
epoch: 13, loss: 0.1826438009738922
epoch: 13, loss: 0.11457307636737823
epoch: 13, loss: 0.10440075397491455
epoch: 14, loss: 0.1755731701850891
epoch: 14, loss: 0.3294568657875061
epoch: 14, loss: 0.13236552476882935
epoch: 14, loss: 0.16628099977970123
epoch: 14, loss: 0.21477434039115906
epoch: 14, loss: 0.17131012678146362
epoch: 14, loss: 0.1364637017250061
epoch: 14, loss: 0.1922212839126587
epoch: 14, loss: 0.23352475464344025
epoch: 14, loss: 0.20792840421199799
epoch: 14, loss: 0.22473134100437164
epoch: 14, loss: 0.17390981316566467
epoch: 14, loss: 0.1926766186952591
epoch: 14, loss: 0.17039641737937927
epoch: 14, loss: 0.11736001819372177
epoch: 15, loss: 0.14264868199825287
epoch: 15, loss: 0.18928661942481995
epoch: 15, loss: 0.21067896485328674
epoch: 15, loss: 0.2726966142654419
epoch: 15, loss: 0.12206914275884628
epoch: 15, loss: 0.13314947485923767
epoch: 15, loss: 0.1376732736825943
epoch: 15, loss: 0.1445278376340866
epoch: 15, loss: 0.2518361210823059
epoch: 15, loss: 0.1964091956615448
epoch: 15, loss: 0.24728693068027496
epoch: 15, loss: 0.1340319812297821
epoch: 15, loss: 0.16541752219200134
epoch: 15, loss: 0.28519389033317566
epoch: 15, loss: 0.1627727895975113
epoch: 16, loss: 0.24798090755939484
epoch: 16, loss: 0.17198629677295685
epoch: 16, loss: 0.25997450947761536
epoch: 16, loss: 0.12939679622650146
epoch: 16, loss: 0.17931871116161346
epoch: 16, loss: 0.1482735574245453
epoch: 16, loss: 0.09587525576353073
epoch: 16, loss: 0.16187067329883575
epoch: 16, loss: 0.14578749239444733
epoch: 16, loss: 0.11343744397163391
epoch: 16, loss: 0.17512071132659912
epoch: 16, loss: 0.262031227350235
epoch: 16, loss: 0.2077321857213974
epoch: 16, loss: 0.24911552667617798
epoch: 16, loss: 0.22738221287727356
epoch: 17, loss: 0.20532622933387756
epoch: 17, loss: 0.16031979024410248
epoch: 17, loss: 0.195382222533226
epoch: 17, loss: 0.21974384784698486
epoch: 17, loss: 0.16546645760536194
epoch: 17, loss: 0.1805814802646637
epoch: 17, loss: 0.17528462409973145
epoch: 17, loss: 0.15540118515491486
epoch: 17, loss: 0.17347243428230286
epoch: 17, loss: 0.13333767652511597
epoch: 17, loss: 0.12817071378231049
epoch: 17, loss: 0.19212348759174347
epoch: 17, loss: 0.237666517496109
epoch: 17, loss: 0.17131321132183075
epoch: 17, loss: 0.18507488071918488
epoch: 18, loss: 0.20904752612113953
epoch: 18, loss: 0.11102636903524399
epoch: 18, loss: 0.17001521587371826
epoch: 18, loss: 0.15238547325134277
epoch: 18, loss: 0.20557592809200287
epoch: 18, loss: 0.17708687484264374
epoch: 18, loss: 0.18823468685150146
epoch: 18, loss: 0.29043272137641907
epoch: 18, loss: 0.14558453857898712
epoch: 18, loss: 0.1110546812415123
epoch: 18, loss: 0.21436211466789246
epoch: 18, loss: 0.10106758773326874
epoch: 18, loss: 0.16903603076934814
epoch: 18, loss: 0.2015887051820755
epoch: 18, loss: 0.13031364977359772
epoch: 19, loss: 0.21065479516983032
epoch: 19, loss: 0.18784160912036896
epoch: 19, loss: 0.15760765969753265
epoch: 19, loss: 0.16713546216487885
epoch: 19, loss: 0.14938241243362427
epoch: 19, loss: 0.24919478595256805
epoch: 19, loss: 0.10713235288858414
epoch: 19, loss: 0.22555382549762726
epoch: 19, loss: 0.16881877183914185
epoch: 19, loss: 0.1552746295928955
epoch: 19, loss: 0.146346315741539
epoch: 19, loss: 0.16269658505916595
epoch: 19, loss: 0.15618588030338287
epoch: 19, loss: 0.12051021307706833
epoch: 19, loss: 0.2562638223171234
epoch: 20, loss: 0.2332455962896347
epoch: 20, loss: 0.13650552928447723
epoch: 20, loss: 0.2204817235469818
epoch: 20, loss: 0.1461886465549469
epoch: 20, loss: 0.17006225883960724
epoch: 20, loss: 0.1364591270685196
epoch: 20, loss: 0.2067754566669464
epoch: 20, loss: 0.1377178579568863
epoch: 20, loss: 0.22296646237373352
epoch: 20, loss: 0.150731161236763
epoch: 20, loss: 0.19465166330337524
epoch: 20, loss: 0.1310405731201172
epoch: 20, loss: 0.1515711396932602
epoch: 20, loss: 0.10993216931819916
epoch: 20, loss: 0.107597716152668
epoch: 21, loss: 0.20723360776901245
epoch: 21, loss: 0.19336996972560883
epoch: 21, loss: 0.1674090176820755
epoch: 21, loss: 0.15213170647621155
epoch: 21, loss: 0.11799375712871552
epoch: 21, loss: 0.1361297070980072
epoch: 21, loss: 0.2522505521774292
epoch: 21, loss: 0.13602976500988007
epoch: 21, loss: 0.12104213237762451
epoch: 21, loss: 0.1586754024028778
epoch: 21, loss: 0.22387419641017914
epoch: 21, loss: 0.11579979956150055
epoch: 21, loss: 0.11264675110578537
epoch: 21, loss: 0.2180900126695633
epoch: 21, loss: 0.058047156780958176
epoch: 22, loss: 0.12544648349285126
epoch: 22, loss: 0.1570131480693817
epoch: 22, loss: 0.12014010548591614
epoch: 22, loss: 0.18498757481575012
epoch: 22, loss: 0.20504602789878845
epoch: 22, loss: 0.19028955698013306
epoch: 22, loss: 0.1165294274687767
epoch: 22, loss: 0.11438025534152985
epoch: 22, loss: 0.12285439670085907
epoch: 22, loss: 0.21620763838291168
epoch: 22, loss: 0.1581500768661499
epoch: 22, loss: 0.15972331166267395
epoch: 22, loss: 0.204609677195549
epoch: 22, loss: 0.16102366149425507
epoch: 22, loss: 0.2145415097475052
epoch: 23, loss: 0.23602807521820068
epoch: 23, loss: 0.20055028796195984
epoch: 23, loss: 0.15586477518081665
epoch: 23, loss: 0.17393353581428528
epoch: 23, loss: 0.14820878207683563
epoch: 23, loss: 0.12963339686393738
epoch: 23, loss: 0.13456764817237854
epoch: 23, loss: 0.15702946484088898
epoch: 23, loss: 0.09729750454425812
epoch: 23, loss: 0.17591598629951477
epoch: 23, loss: 0.19306215643882751
epoch: 23, loss: 0.19487084448337555
epoch: 23, loss: 0.11091279238462448
epoch: 23, loss: 0.1185489073395729
epoch: 23, loss: 0.08057190477848053
epoch: 24, loss: 0.19646020233631134
epoch: 24, loss: 0.139973983168602
epoch: 24, loss: 0.19445562362670898
epoch: 24, loss: 0.10126522928476334
epoch: 24, loss: 0.11579721421003342
epoch: 24, loss: 0.13746629655361176
epoch: 24, loss: 0.1323818564414978
epoch: 24, loss: 0.157918319106102
epoch: 24, loss: 0.22127151489257812
epoch: 24, loss: 0.15118463337421417
epoch: 24, loss: 0.2392640858888626
epoch: 24, loss: 0.13754016160964966
epoch: 24, loss: 0.15776264667510986
epoch: 24, loss: 0.09631169587373734
epoch: 24, loss: 0.13077731430530548
epoch: 25, loss: 0.1947631537914276
epoch: 25, loss: 0.1367073953151703
epoch: 25, loss: 0.09863835573196411
epoch: 25, loss: 0.24074144661426544
epoch: 25, loss: 0.11988241970539093
epoch: 25, loss: 0.14427174627780914
epoch: 25, loss: 0.14719034731388092
epoch: 25, loss: 0.1368529200553894
epoch: 25, loss: 0.12011393159627914
epoch: 25, loss: 0.1962776631116867
epoch: 25, loss: 0.12078015506267548
epoch: 25, loss: 0.12713299691677094
epoch: 25, loss: 0.16604554653167725
epoch: 25, loss: 0.12995171546936035
epoch: 25, loss: 0.42731449007987976

In [45]:
model.parameters

<bound method Module.parameters of MySimpleNN(
  (linear): Linear(in_features=30, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)>

Model Eval (Old)

In [46]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'accuracy: {accuracy.item()}')

accuracy: 0.5400123000144958

In [47]:
y_pred.shape

torch.Size([114, 1])

In [48]:
batch_labels.shape

torch.Size([7])

Model Eval (New)

In [51]:
model.eval()

accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model.forward(batch_features)
    y_pred = (y_pred > 0.9).float()

    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean()

    accuracy_list.append(batch_accuracy.item())

print(f'accuracy: {np.mean(accuracy_list)}')

accuracy: 0.9331597238779068

In [52]:
accuracy_list

[0.9375, 0.9375, 0.96875, 0.8888888955116272]

In [28]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [29]:
from torchinfo import summary

In [30]:
summary(model, input_size=X_train_tensor.shape)

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================